
CREATE TABLE BROKER_STATS(

  TS        TIMESTAMP NOT NULL,
  SERVICE   VARCHAR(64) NOT NULL,

  MIN       INTEGER,
  MAX       INTEGER,
  AVG       INTEGER,
  COUNT     INTEGER,

  PRIMARY KEY(TS, SERVICE)
);

